FROM cypress/base:8
RUN apt-get update && \
    apt-get install -y \
      netcat && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /home

COPY package.json package-lock.json /home/

# Install selected package (faster).
# Use versions defined in package-lock.json.
RUN git config --global url."https://".insteadOf git:// && \
    git config --global url."https://github.com/".insteadOf git@github.com: && \
    npm install \
      cypress@`node -p -e "require('./package-lock.json').dependencies.cypress.version"` \
      bluebird@`node -p -e "require('./package-lock.json').dependencies.bluebird.version"`

COPY src /home/src
COPY test /home/test
COPY scripts /home/scripts
COPY package.json cypress.json /home/
