FROM node:8.9 AS build-deps

MAINTAINER datapunt.ois@amsterdam.nl

WORKDIR /app

# Install sluggish packages ahead of time
RUN npm install cypress phantomjs-prebuilt && \
    npm cache clean --force

COPY package.json package-lock.json /app/

# Changing git URL because network is blocking git protocol...
RUN git config --global url."https://".insteadOf git:// && \
    git config --global url."https://github.com/".insteadOf git@github.com: && \
    npm --production=false \
        --unsafe-perm \
        --verbose \
        install  && \
    npm cache clean --force

COPY . /app

ENV NODE_ENV=production
ARG BUILD_ENV=prod
RUN npm run build-${BUILD_ENV}

FROM nginx:1.12.2-alpine
COPY --from=build-deps /app/dist /usr/share/nginx/html
