FROM cypress/base:10
RUN apt-get update && \
    apt-get install -y \
      netcat && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /home

COPY package.json package-lock.json /home/

# Install selected package (faster).
# Use versions defined in package-lock.json.
# `npm install` with `CI=true` is to stop cypress install progress from flooding the CI log
RUN git config --global url."https://".insteadOf git:// && \
    git config --global url."https://github.com/".insteadOf git@github.com: && \
    CI=true npm install \
      cypress@`node -p -e "require('./package-lock.json').dependencies.cypress.version"` \
      bluebird@`node -p -e "require('./package-lock.json').dependencies.bluebird.version"`

COPY src /home/src
COPY test /home/test
COPY scripts /home/scripts
COPY package.json package-lock.json cypress.json /home/
