FROM cypress/base:8
RUN apt-get update && \
    apt-get install -y \
      netcat && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /home

COPY package-lock.json /home/

# Install selected package (faster).
# Use versions defined in package-lock.json.
RUN npm install \
  cypress@`node -p -e "require('./package-lock.json').dependencies.cypress.version"` \
  bluebird@`node -p -e "require('./package-lock.json').devDependencies.bluebird.version"`

COPY src /home/src
COPY test /home/test
COPY scripts /home/scripts
COPY package.json cypress.json /home/
