export default {
  QUERY: 'term',
  SORT: 'sortering',
  MAP_BACKGROUND: 'achtergrond',
  PAGE: 'pagina',
  GEO: 'geo',
  VIEW: 'modus',
  CATEGORY: 'categorie',
  VIEW_CENTER: 'center',
  ZOOM: 'zoom',
  LEGEND: 'legenda',
  HEADING: 'heading',
  PANORAMA_TAGS: 'tags',
  PITCH: 'pitch',
  FILTERS: 'filters',
  SEARCH_FILTERS: 'zoek-filters',
  DETAIL_REFERENCE: 'detail-ref',
  PAGE_REFERENCE: 'page-ref',
  EMBED_PREVIEW: 'embed-preview',
  EMBED: 'embed',
  PRINT: 'print',
  LAYERS: 'lagen',
  LOCATION: 'locatie',
  FILE: 'bestand',
  MARKER: 'marker',
  MARKER_ICON: 'marker-icon',
  MAP_LINK: 'map-link',
}
