export const REQUEST_GEOSEARCH = 'REQUEST_GEOSEARCH';
export const REQUEST_NEAREST_DETAILS = 'REQUEST_NEAREST_DETAILS';

export default {
  SHOW_DATA_SELECTION: 'SHOW_DATA_SELECTION',
  NAVIGATE_DATA_SELECTION: 'NAVIGATE_DATA_SELECTION',
  SET_DATA_SELECTION_VIEW: 'SET_DATA_SELECTION_VIEW',

  // ignore
  MAP_CLICK: 'MAP_CLICK',
  RESET_DATA_SELECTION: 'RESET_DATA_SELECTION'
};
