export const REDUCER_KEY = 'dataSearch';
export const FETCH_MAP_SEARCH_RESULTS_REQUEST = `${REDUCER_KEY}/FETCH_MAP_SEARCH_RESULTS_REQUEST`;
export const FETCH_MAP_SEARCH_RESULTS_FAILURE = `${REDUCER_KEY}/FETCH_MAP_SEARCH_RESULTS_FAILURE`;
export const FETCH_MAP_SEARCH_RESULTS_SUCCESS_PANEL = `${REDUCER_KEY}/FETCH_MAP_SEARCH_RESULTS_SUCCESS_PANEL`;
export const FETCH_MAP_SEARCH_RESULTS_SUCCESS_LIST = `${REDUCER_KEY}/FETCH_MAP_SEARCH_RESULTS_SUCCESS_LIST`;

export const FETCH_QUERY_SEARCH_RESULTS_REQUEST = `${REDUCER_KEY}/FETCH_QUERY_SEARCH_RESULTS_REQUEST`;
export const FETCH_QUERY_SEARCH_RESULTS_SUCCESS = `${REDUCER_KEY}/FETCH_QUERY_SEARCH_RESULTS_SUCCESS`;
export const FETCH_QUERY_SEARCH_RESULTS_FAILURE = `${REDUCER_KEY}/FETCH_QUERY_SEARCH_RESULTS_FAILURE`;

export const FETCH_QUERY_SEARCH_MORE_RESULTS_REQUEST = `${REDUCER_KEY}/FETCH_QUERY_SEARCH_MORE_RESULTS_REQUEST`;
export const FETCH_QUERY_SEARCH_MORE_RESULTS_SUCCESS = `${REDUCER_KEY}/FETCH_QUERY_SEARCH_MORE_RESULTS_SUCCESS`;
export const FETCH_QUERY_SEARCH_MORE_RESULTS_FAILURE = `${REDUCER_KEY}/FETCH_QUERY_SEARCH_MORE_RESULTS_FAILURE`;

export const SET_QUERY_CATEGORY = `${REDUCER_KEY}/SET_QUERY_CATEGORY`;
export const SET_GEO_LOCATION = `${REDUCER_KEY}/SET_GEO_LOCATION`;

export const initialState = {
  resultsMapPanel: [],
  resultsMap: [],
  resultsQuery: [],
  isLoading: false,
  numberOfResults: 0,
  category: null,
  error: null
};

export const SEARCH_VIEW = {
  MAP_SEARCH: 'MAP_SEARCH',
  SEARCH: 'SEARCH'
};
