const mockApiData = {
  components: {
    schemas: {
      'dcat-dataset': {
        properties: {
          'ams:license': {
            default: 'unspec',
            description: 'Geef aan onder welke open data licentie de gegevensset gepubliceerd is, indien van toepassing. Gebruik invulhulp om licentie te bepalen. Indien er sprake is van een gedeeltelijk publieke dataset, dan geldt de licentie voor het publieke deel.',
            enum: [
              'cc-by',
              'cc-by-nc',
              'cc-by-nc-nd',
              'cc-by-nc-sa',
              'cc-by-nd',
              'cc-by-sa',
              'cc-nc',
              'cc-zero',
              'other-open',
              'other-by',
              'other-nc',
              'other-not-open',
              'unspec'
            ],
            enumNames: [
              'Creative Commons, Naamsvermelding',
              'Creative Commons, Naamsvermelding, Niet-Commercieel',
              'Creative Commons, Naamsvermelding, Niet-Commercieel, Geen Afgeleide Werken',
              'Creative Commons, Naamsvermelding, Niet-Commercieel, Gelijk Delen',
              'Creative Commons, Naamsvermelding, Geen Afgeleide Werken',
              'Creative Commons, Naamsvermelding, Gelijk Delen',
              'Creative Commons, Niet-Commercieel',
              'Publiek Domein',
              'Anders, Open',
              'Anders, Naamsvermelding',
              'Anders, Niet Commercieel',
              'Anders, Niet Open',
              'Niet gespecificeerd'
            ],
            minLength: 1,
            title: 'Licentie',
            type: 'string'
          },
          'ams:owner': {
            description: 'Eigenaar en verantwoordelijke voor de betreffende registratie, ook wel bronhouder genoemd. Bij de overheid is dit het bestuursorgaan of rechtspersoon aan wie bij wettelijk voorschrift de verantwoordelijkheid voor het bijhouden van gegevens in een registratie is opgedragen.',
            examples: [
              'AEB Amsterdam',
              'Adrian Inc.',
              'Amsterdam Economic Board',
              'Amsterdam Marketing',
              'Amsterdam Museum',
              'Athlon Car Lease',
              'Brandweer Amsterdam-Amstelland',
              'CBS',
              'CIBG',
              'Cliëntenbelang',
              'Cultuurcompagnie Noord-Holland',
              'Druif Design',
              'GGD Amsterdam',
              'GOVI',
              'Gemeente Amsterdam',
              'Gemeente Amsterdam, Basisinformatie',
              'Gemeente Amsterdam, Bestuur en Organisatie',
              'Gemeente Amsterdam, Economie',
              'Gemeente Amsterdam, Grond en Ontwikkeling',
              'Gemeente Amsterdam, Monumenten en Archeologie',
              'Gemeente Amsterdam, Onderwijs, Jeugd en Zorg',
              'Gemeente Amsterdam, Onderzoek, Informatie en Statistiek',
              'Gemeente Amsterdam, Projectmanagementbureau',
              'Gemeente Amsterdam, Ruimte en Duurzaamheid',
              'Gemeente Amsterdam, Sport en Bos',
              'Gemeente Amsterdam, Stadsarchief',
              'Gemeente Amsterdam, Stadsdeel Centrum',
              'Gemeente Amsterdam, Stadsdeel West',
              'Gemeente Amsterdam, Verkeer en Openbare Ruimte',
              'Gemeente Amsterdam, Wonen',
              'Gemeente Amsterdam, programma Afval Keten',
              'Gemeente Amsterdam, stadsdeel Zuidoost',
              'JeKuntMeer.nl',
              'KNMI',
              'Kadaster',
              'Landelijk Register Kinderopvang en Peuterspeelzalen',
              'Liander',
              'Ministerie van OCW',
              'Nationale Databank Wegverkeergegevens',
              'Nieuwe organisatie',
              'Open Cultuur Data',
              'Peter J B',
              'Politie Amsterdam-Amstelland',
              'Rijksdienst voor Cultureel Erfgoed',
              'Rijksdienst voor Ondernemend Nederland',
              'Rijksmuseum Amsterdam',
              'Rijkswaterstaat',
              'UWV',
              'Waag Society',
              'nico',
              'q'
            ],
            minLength: 1,
            pattern: '^[^\\n\\r]*?\\S[^\\n\\r]*$',
            title: 'Eigenaar',
            type: 'string'
          },
          'ams:spatialDescription': {
            minLength: 1,
            pattern: '^[^\\n\\r]*?\\S[^\\n\\r]*$',
            title: 'Omschrijving gebied',
            type: 'string'
          },
          'ams:spatialUnit': {
            default: 'na',
            enum: [
              'na',
              'specific',
              'nation',
              'region',
              'city',
              'district',
              'area',
              'borrow',
              'neighborhood',
              'block',
              'zip4',
              'zip5',
              'zip6',
              'other'
            ],
            enumNames: [
              'Geen geografie',
              'Specifieke punten/vlakken/lijnen',
              'Land',
              'Regio',
              'Gemeente',
              'Stadsdeel',
              'Gebied',
              'Wijk',
              'Buurt',
              'Bouwblok',
              'Postcode (4 cijfers)',
              'Postcode (4 cijfers, 1 letter)',
              'Postcode (4 cijfers, 2 letters)',
              'anders'
            ],
            minLength: 1,
            title: 'Gebiedseenheid',
            type: 'string'
          },
          'ams:temporalUnit': {
            default: 'na',
            enum: [
              'na',
              'realtime',
              'minutes',
              'hours',
              'parttime',
              'days',
              'weeks',
              'months',
              'quarters',
              'years',
              'other'
            ],
            enumNames: [
              'Geen tijdseenheid',
              'Realtime',
              'Minuten',
              'Uren',
              'Dagdelen',
              'Dagen',
              'Weken',
              'Maanden',
              'Kwartalen',
              'Jaren',
              'anders'
            ],
            minLength: 1,
            title: 'Tijdseenheid',
            type: 'string'
          },
          'dcat:contactPoint': {
            properties: {
              'vcard:fn': {
                description: 'Geef de naam van de contactpersoon voor eventuele vragen over de inhoud en kwaliteit van de gegevens.',
                minLength: 1,
                pattern: '^[^\\n\\r]*?\\S[^\\n\\r]*$',
                title: 'Inhoudelijk contactpersoon',
                type: 'string'
              },
              'vcard:hasEmail': {
                format: 'email',
                minLength: 1,
                title: 'E-mail inhoudelijk contactpersoon',
                type: 'string'
              },
              'vcard:hasURL': {
                format: 'uri',
                minLength: 1,
                title: 'Website inhoudelijk contactpersoon',
                type: 'string'
              }
            },
            required: [
              'vcard:fn'
            ],
            title: '',
            type: 'object',
            'x-order': [
              'vcard:fn',
              'vcard:hasEmail',
              'vcard:hasURL'
            ]
          },
          'dcat:distribution': {
            default: [],
            items: {
              properties: {
                'ams:classification': {
                  enum: [
                    'public'
                  ],
                  enumNames: [
                    'Publiek toegankelijk'
                  ],
                  minLength: 1,
                  title: 'Classification',
                  type: 'string'
                },
                'ams:distributionType': {
                  enum: [
                    'api',
                    'file',
                    'web'
                  ],
                  enumNames: [
                    'API/Service',
                    'Bestand',
                    'Website'
                  ],
                  minLength: 1,
                  title: 'Verschijningsvorm',
                  type: 'string'
                },
                'ams:layerIdentifier': {
                  description: 'De Citydata kaartlaag waarmee deze dataset op de kaart getoond kan worden',
                  minLength: 1,
                  pattern: '^[^\\n\\r]*?\\S[^\\n\\r]*$',
                  title: 'Interne Kaartlaag ID',
                  type: 'string'
                },
                'ams:resourceType': {
                  enum: [
                    'data',
                    'doc',
                    'vis',
                    'app'
                  ],
                  enumNames: [
                    'Data',
                    'Documentatie',
                    'Visualisatie',
                    'Voorbeeldtoepassing'
                  ],
                  minLength: 1,
                  title: 'Type resource',
                  type: 'string'
                },
                'ams:serviceType': {
                  description: 'Geef het type API of webservice',
                  enum: [
                    'atom',
                    'rest',
                    'csw',
                    'wcs',
                    'wfs',
                    'wms',
                    'wmts',
                    'soap',
                    'other'
                  ],
                  enumNames: [
                    'REST: Atom feed',
                    'REST: overig',
                    'CSW',
                    'WCS',
                    'WFS',
                    'WMS',
                    'WMTS',
                    'SOAP',
                    'Anders'
                  ],
                  minLength: 1,
                  title: 'Type API/Service',
                  type: 'string'
                },
                'dcat:accessURL': {
                  description: 'Toegangslink naar de daadwerkelijke gegevensset óf downloadlink om gegevensset te downloaden',
                  format: 'uri',
                  minLength: 1,
                  title: 'URL of upload',
                  type: 'string'
                },
                'dcat:byteSize': {
                  description: 'Bestandsgrootte in bytes',
                  minimum: 0,
                  title: 'Bestandsgrootte',
                  type: 'number'
                },
                'dct:description': {
                  minLength: 1,
                  title: 'Beschrijving',
                  type: 'string'
                },
                'dct:format': {
                  enum: [
                    'n/a',
                    'text/csv',
                    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                    'application/vnd.geo+json',
                    'application/gml+xml',
                    'text/html',
                    'application/json',
                    'application/pdf',
                    'image/png',
                    'application/zip; format=\'shp\'',
                    'application/vnd.ms-excel',
                    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                    'application/xml',
                    'application/octet-stream'
                  ],
                  enumNames: [
                    '',
                    'CSV',
                    'DOCX',
                    'GeoJSON',
                    'GML',
                    'HTML',
                    'JSON',
                    'PDF',
                    'PNG',
                    'SHP',
                    'XLS',
                    'XLSX',
                    'XML',
                    'Anders'
                  ],
                  minLength: 1,
                  title: 'Type bestand',
                  type: 'string'
                },
                'dct:modified': {
                  default: '2018-07-10',
                  description: 'De datum waarop de inhoud van deze link voor het laatst is geactualiseerd.',
                  format: 'date',
                  minLength: 1,
                  pattern: '^\\d\\d\\d\\d-[01]\\d-[0-3]\\d(?:T[012]\\d:[0-5]\\d:[0-5]\\d(?:\\.\\d+)?)?(?:Z|[01]\\d(?::[0-5]\\d)?)?$',
                  title: 'Verversingsdatum',
                  type: 'string'
                },
                'dct:title': {
                  minLength: 1,
                  pattern: '^[^\\n\\r]*?\\S[^\\n\\r]*$',
                  title: 'Titel',
                  type: 'string'
                },
                'foaf:isPrimaryTopicOf': {
                  properties: {
                    'dct:issued': {
                      default: '2018-07-10',
                      description: 'De datum waarop deze beschrijving van de gegevensset beschikbaar is gesteld',
                      format: 'date',
                      minLength: 1,
                      pattern: '^\\d\\d\\d\\d-[01]\\d-[0-3]\\d(?:T[012]\\d:[0-5]\\d:[0-5]\\d(?:\\.\\d+)?)?(?:Z|[01]\\d(?::[0-5]\\d)?)?$',
                      title: 'Publicatiedatum',
                      type: 'string'
                    },
                    'dct:modified': {
                      default: '2018-07-10',
                      description: 'De datum waarop deze beschrijving van de gegevensset voor het laatst is gewijzigd',
                      format: 'date',
                      minLength: 1,
                      pattern: '^\\d\\d\\d\\d-[01]\\d-[0-3]\\d(?:T[012]\\d:[0-5]\\d:[0-5]\\d(?:\\.\\d+)?)?(?:Z|[01]\\d(?::[0-5]\\d)?)?$',
                      sysDefined: true,
                      title: 'Wijzigingsdatum',
                      type: 'string'
                    }
                  },
                  required: [
                    'dct:modified'
                  ],
                  title: '',
                  type: 'object',
                  'x-order': [
                    'dct:issued',
                    'dct:modified'
                  ]
                }
              },
              required: [
                'dct:title',
                'dcat:accessURL',
                'ams:resourceType',
                'ams:distributionType',
                'foaf:isPrimaryTopicOf'
              ],
              type: 'object',
              'x-order': [
                'dct:title',
                'dct:description',
                'dcat:accessURL',
                'ams:resourceType',
                'ams:distributionType',
                'ams:serviceType',
                'dct:format',
                'ams:layerIdentifier',
                'dct:modified',
                'ams:classification',
                'dcat:byteSize',
                'foaf:isPrimaryTopicOf'
              ]
            },
            title: 'Resources',
            type: 'array'
          },
          'dcat:keyword': {
            default: [],
            items: {
              examples: [
                '14.000 ft',
                '14020',
                '2.5D',
                '20Ke',
                '360 graden foto',
                '3D',
                '50 dbA-contour',
                'AHN',
                'API',
                'Adres',
                'Adrian',
                'Afval',
                'Aikido',
                'Amersfoort',
                'Amsterdam',
                'Amsterdam Zuidoost',
                'Apotheek',
                'Arbeidsmarkt',
                'Arena',
                'Auto',
                'BAG',
                'BI',
                'BIG',
                'BRK',
                'BRT',
                'BSO',
                'Badminton',
                'Basismeetset',
                'Basisregistratie',
                'Basisregistratie kadaster',
                'Basketbal',
                'Bedrijfstak',
                'Beperkingengebied',
                'Bestemming',
                'Boksen',
                'Boswet',
                'Buitenschoolse',
                'Buurtcombinaties',
                'Buurten',
                'CBS',
                'CCTV',
                'CIR',
                'COROP',
                'Capoeira',
                'Cijfers',
                'City',
                'CitySDK',
                'Dans',
                'Data',
                'Datapunt',
                'Demografie',
                'Demografische druk',
                'Economie',
                'Energie',
                'Europa',
                'Europe',
                'European',
                'Europees',
                'Evenementen',
                'Feiten',
                'Fiets',
                'Gastouderopvang',
                'Gastouders',
                'Gebiedsindeling',
                'Gebiedsindelingstadsdelen',
                'Gehandicaptenparkeerplaatsen',
                'Grijze druk',
                'Groene druk',
                'Grofvuil',
                'Groot-Amsterdam',
                'Grootschalig',
                'H2020',
                'HIV',
                'HR',
                'Haha',
                'Handelsregister',
                'Hockey',
                'Horeca Informatie Systeem',
                'Horizon 2020',
                'Huddesteen',
                'ICC',
                'ICT',
                'IV3',
                'Industrielawaai',
                'Infrastructuur',
                'Innovatie',
                'Judo',
                'KBKA',
                'KDV',
                'Kadaster',
                'Kamer',
                'Kamer van Koophandel',
                'Kamer van koophandel',
                'Kanoën',
                'Karate',
                'Kinderdagverblijf',
                'Kinderen',
                'Klimmen',
                'Korfbal',
                'Krav',
                'Krijgskunst',
                'KvK',
                'LIB',
                'LIB-4',
                'LVNL',
                'Leven',
                'Linked',
                'Luchthavenindelingbesluit',
                'MIT',
                'MOOR',
                'MORA',
                'Maga',
                'Meldkamer, brandweer, politie, zwaailicht',
                'Metropoolregio Amsterdam',
                'Mismatch',
                'NAP',
                'NEN',
                'NPR',
                'Normaal Amsterdams Peil',
                'OV',
                'Omnisportvereniging',
                'Onderzoek',
                'Opleiding',
                'Opvang',
                'PC4',
                'PC5',
                'PC6',
                'PM10',
                'PM2.5',
                'PP6',
                'PR',
                'PSZ',
                'Parkeren',
                'Parlement',
                'Peuterspeelzaal',
                'Peuterspeelzalen',
                'Plusnet',
                'Postcode',
                'Postcode6',
                'Postcodes',
                'Provinciale',
                'RCE',
                'RD',
                'RDA',
                'RGB',
                'RVE',
                'RVO',
                'RWS',
                'Rijkswaterstaat',
                'SDK',
                'Schaken',
                'Schietsportvereniging',
                'Schiphol',
                'Sjoelen',
                'Sportschool',
                'Stadsdelen',
                'Staten',
                'Statistiek',
                'Taekwon-Do',
                'Tafeltennis',
                'Talent voor de Toekomst',
                'Tellus',
                'Tennis',
                'Top10NL',
                'Top50NL',
                'Turnen',
                'Tweede',
                'Tweede Kamer',
                'Tweede kamer',
                'UNESCO',
                'UWV',
                'Ultracam Eagle camera',
                'VGO',
                'VOR',
                'VVE',
                'Verkeer',
                'Voetbal',
                'Voetganger',
                'Volleybal',
                'WBSO',
                'WKO',
                'WOII',
                'Wegenverkeerswet',
                'West',
                'Wkpb',
                'Yoga',
                'Zelfverdediging',
                'Ziggo dome',
                'Zomerse',
                'Zwemmen',
                'aanbieden grofvuil',
                'aanbod',
                'aanduiding in onderzoek',
                'aangewezen',
                'aanhoudingen',
                'aantal',
                'aantal kamers',
                'aantasting',
                'accounts',
                'achtergrond',
                'activiteiten',
                'actueel',
                'actueel hoogtebestand Nederland',
                'adressen',
                'adrian',
                'afval',
                'afval ophaalgebied',
                'afval ophaalgebieden',
                'afvalbak',
                'afvalbakken',
                'afvalcontainers',
                'afvalophaalgebied',
                'afvalophaalgebieden',
                'afvalpunt',
                'afvalregels',
                'afvalregels per locatie',
                'afvalscheiding',
                'afweergeschut',
                'agenda',
                'agent',
                'alcoholverbodgebieden',
                'amsterdam',
                'and',
                'apotheken',
                'appartement',
                'appartementen',
                'appartementsrecht',
                'appartementsrechten',
                'arbeidsmarkt',
                'arbeidsongeschiktheid',
                'arbeidsproductiviteit',
                'archeologie',
                'architect',
                'architecten',
                'architectuur',
                'armoede',
                'artsen',
                'atcb',
                'atelierpand',
                'attracties',
                'auto',
                'autobezit',
                'autos',
                'balie',
                'banen',
                'bar',
                'barometer',
                'basiskaart',
                'basisonderwijs',
                'basisregistratie',
                'basisregistratie adressen en gebouwen',
                'basisscholen',
                'basisschool',
                'basisschooladviezen',
                'bassie',
                'bassieenadriaan',
                'baten',
                'bebouwde kom',
                'bedden',
                'bedrijf',
                'bedrijfstak',
                'bedrijfsvaerzamelgebouwen',
                'bedrijfsvestigingen',
                'bedrijven',
                'beeldbank',
                'beelden',
                'beeldhouwkunst',
                'begroting',
                'bekendmakingen',
                'bekeuringen',
                'belang',
                'belangenbehartiging',
                'belastingen',
                'belemmering',
                'belemmeringen',
                'bepaal ik zelf',
                'beperking',
                'beperkingen',
                'beroepsbevolking',
                'beroepsonderwijs',
                'beschermde dorpsgezichten',
                'beschermde stadsgezichten',
                'beschikbaar',
                'beschikbaarheid',
                'bestedingen',
                'bestemmingsplan',
                'bestemmingsplannen',
                'beurs',
                'bevolking',
                'bevolkingsdichtheid',
                'bevolkingsgroei',
                'bevolkingsprognose',
                'bezetting',
                'bezettingsgraad',
                'bezienswaardigheden',
                'bi',
                'bijen',
                'bijstand',
                'bijzonder',
                'biologische',
                'bioscoop',
                'blokeenheid',
                'bodemkwaliteit',
                'boeken',
                'boeren',
                'boerenmarkten',
                'bom',
                'bomen',
                'bommenkaart',
                'boom',
                'boswet',
                'bout',
                'bouten',
                'bouw',
                'bouwblok',
                'bouwblokken',
                'bouwblokzijde',
                'bouwen',
                'bouwjaar',
                'bouwjaren',
                'bouwrijp',
                'bouwvergunning',
                'braakliggend',
                'branches',
                'brand',
                'branden',
                'brandweer',
                'broedplaats',
                'bromfiets',
                'brug',
                'bruggen',
                'buddy',
                'budget',
                'buien',
                'bureau',
                'burgerlijke',
                'burgerlijke staat',
                'bus',
                'businesslocatie',
                'bussen',
                'buurt',
                'buurtcentra',
                'buurtcentrum',
                'buurtcombinatie',
                'buurtcombinaties',
                'buurten',
                'buurthuis',
                'buurthuizen',
                'buurtindeling',
                'buurtwerk',
                'cabaret',
                'cafe',
                'cafes',
                'cameras',
                'capaciteit',
                'cartografie',
                'casino',
                'catalogus',
                'cbs',
                'centrum',
                'chemisch afval',
                'circulaire economie',
                'circus',
                'cito',
                'classificatie',
                'clinics',
                'cohesie',
                'collectie',
                'collectief',
                'compleet',
                'congres',
                'congressen',
                'containers',
                'corporaties',
                'creatieve industrie',
                'csv',
                'cultureel',
                'cultuur',
                'cultuurhistorie',
                'dagbesteding',
                'daken',
                'daklozen',
                'daklozenzorg',
                'dans',
                'data',
                'deformatie',
                'dementie',
                'demografie',
                'detail',
                'detailhandel',
                'detaillering',
                'dienst werk en inkomen',
                'diensten',
                'dienstencentra',
                'dienstverlening',
                'distribution',
                'documenten',
                'doden',
                'doelgroepleerlingen',
                'doodsoorzaken',
                'drempels',
                'drinkwater',
                'drugs',
                'drukte',
                'dubbelglas',
                'duurzaamheid',
                'echtscheidende amsterdammer',
                'echtscheiding',
                'echtscheidingen',
                'ecologie',
                'ecologisch',
                'ecologische',
                'economie',
                'economisch verkeer',
                'eik',
                'eiken',
                'eindtoets',
                'elektriciteit',
                'elektrisch',
                'elektrische',
                'en',
                'energie',
                'energielabels',
                'energieverbruik',
                'erfpacht',
                'eten',
                'etnische groepen',
                'evenementen',
                'evenementenvergunning',
                'excel',
                'exploitatie',
                'exploitatievergunning',
                'explosieven',
                'export',
                'exposities',
                'faillissementen',
                'fauna',
                'faunapassage',
                'feitelijk gebruik',
                'festivals',
                'fiets',
                'fietsen',
                'fietsenstalling',
                'fietsnetwerk',
                'fietspaden',
                'files',
                'film',
                'filtering',
                'financien',
                'financiële instellingen',
                'fontein',
                'food trucks',
                'forensisch arts',
                'fotos',
                'functie',
                'functiekaart',
                'functies',
                'fundering',
                'funderinghoogte',
                'fysiotherapeuten',
                'fysiotherapie',
                'galleries',
                'gas',
                'gbk',
                'gbka',
                'gbkn',
                'gebied',
                'gebieden',
                'gebiedsgericht werken',
                'gebiedsindeling',
                'geboorte',
                'gebouw',
                'gebouwen',
                'gebouwhoogte',
                'gebouwhoogtes',
                'gebruiksdoel',
                'gebruiksdoelen',
                'gebruiksvergunning',
                'gehandicapt',
                'gehandicaptenparkeerplaatsvergunning',
                'geluid',
                'geluidshinder',
                'geluidskaart',
                'geluidsoverlast',
                'geluidzones',
                'gemeente',
                'gemeentebegroting',
                'gemeentefonds',
                'gemeentelijk monument',
                'gemeentelijke beperkingenregistratie',
                'gemeenteraad',
                'gemeenteraadsleden',
                'gemeenterekening',
                'geografie',
                'geometrie',
                'geothermie',
                'geslaagden',
                'geslachtsziekten',
                'gevaarlijke',
                'gewicht',
                'gewonden',
                'gezondheid',
                'gezondheidszorg',
                'gezoneerd industrieterrein',
                'geïnterpoleerd',
                'ggz',
                'gierzwaluw',
                'gis',
                'gladheid',
                'glas',
                'glasbak',
                'goederen',
                'goods',
                'gracht',
                'grachten',
                'granaat',
                'grid',
                'groei',
                'groeicijfers',
                'groen',
                'groene',
                'groenvoorziening',
                'grof vuil',
                'grond',
                'grondgebied',
                'grondgebruik',
                'grondresolutie',
                'grootschalig',
                'grootschalige',
                'grootschalige kaart',
                'grootschalige topografie',
                'grootstedelijk gebied',
                'grootstedelijke gebieden',
                'gvb',
                'gymzaal',
                'gymzalen',
                'halte',
                'haltes',
                'handel',
                'haven',
                'havens',
                'hbo',
                'herbestemming',
                'herhalingsmeting',
                'herkomst',
                'herrie',
                'hinder',
                'historie',
                'historisch',
                'hogescholen',
                'homo',
                'honing',
                'hoofdbewoners',
                'hoofdgroenstructuur',
                'hoogopgeleide',
                'hoogte',
                'hoogtemodel',
                'hoogtes',
                'horeca',
                'hotel',
                'hotelloods',
                'hotels',
                'houtopstanden',
                'huisarts',
                'huisartspraktijk',
                'huishoudelijk',
                'huishoudens',
                'huishoudenstypen',
                'huisletter',
                'huisletters',
                'huisnummer',
                'huisnummers',
                'huisnummertoevoeging',
                'huisnummertoevoegingen',
                'huisvesting',
                'huisvuil',
                'huisvuil ophaalgebied',
                'hulp',
                'hulpverlening',
                'huren',
                'huur',
                'huurprijs',
                'huursubsidie',
                'huurtoeslag',
                'huurwoningen',
                'huwelijk',
                'huwelijken',
                'huwende amsterdammer',
                'ijzel',
                'inburgering',
                'indexcijfers',
                'indicatie geconstateerd',
                'indicaties',
                'individueel',
                'infectieziekten',
                'ingetrokken',
                'inkomen',
                'inkomsten',
                'innovatie',
                'inslagen',
                'instroom',
                'intensiteit',
                'internationaal',
                'internet',
                'invalide',
                'invalideparkeerplaatsen',
                'inwinningsdatum',
                'inzameldag',
                'inzameldagen',
                'ja!',
                'jaap eden',
                'jaarcijfers',
                'jeugd',
                'jeugd-ggz',
                'jeugdgezondheidszorg',
                'jeugdzorg',
                'jeughdhulpverlening',
                'jongeren',
                'jongerenhuisvesting',
                'junioren',
                'kaart',
                'kaart achter de burgemeester',
                'kaartblad',
                'kaarttegels',
                'kadastraal object',
                'kadastraal perceel',
                'kadastraal subject',
                'kadastraalobject',
                'kadastrale aanduiding',
                'kadastrale grens',
                'kadastrale grenzen',
                'kadastrale kaart',
                'kadastrale kaarten',
                'kalender',
                'kamers',
                'kansengebieden',
                'kansenkaart',
                'kantoor',
                'kantoorprijzen',
                'kantoren',
                'kantorenloods',
                'kapvergunning',
                'kartografie',
                'kassen',
                'kastanje',
                'kastanjebloedingsziekte',
                'kastanjebomen',
                'kasteel',
                'kastelen',
                'kavel',
                'kavels',
                'kbk10',
                'kbk50',
                'kbka',
                'kbka10',
                'kbka50',
                'kerk',
                'kerken',
                'kermis',
                'kerncijfers',
                'kernregistratie',
                'kernregistratie monumenten',
                'kiesgerechtigden',
                'kinderboerderij',
                'kinderdagverblijven',
                'kinderopvang',
                'klasse',
                'kleine',
                'kleinschalig',
                'kleinschalige',
                'kleinschalige topografie',
                'klinieken',
                'knnv',
                'koopjaar',
                'koopjaren',
                'koopkrachtbinding',
                'koopsom',
                'koopsommen',
                'koopwoning',
                'kosten',
                'koude',
                'kruidentuin',
                'kruispunten',
                'kunst',
                'kunstwerken',
                'laadnetwerk',
                'laden',
                'laden en lossen',
                'landbouw',
                'landhuis',
                'landhuizen',
                'landschap',
                'landsdekkend',
                'laseraltimetrie',
                'laserpunten',
                'layers',
                'leaseautos',
                'leef',
                'leefbaar',
                'leefgebieden',
                'leefomgevingen',
                'leeftijd',
                'leeftijdsgroepen',
                'leegstaande',
                'leegstand',
                'leerlingen',
                'leerplicht',
                'leisure',
                'lesbisch',
                'levensonderhoud',
                'lhbt',
                'ligging',
                'ligweide',
                'linked',
                'literatuur',
                'live',
                'live uitzendingen',
                'logies',
                'logiesvormen',
                'logopedie',
                'logopedisten',
                'loketten',
                'loop van de bevolking',
                'lossen',
                'luchtaanval',
                'luchthaven',
                'luchtkwaliteit',
                'luchtmetingen',
                'maaiveld',
                'maatje',
                'maatschappelijke activiteiten',
                'maatschappelijke organisaties',
                'macro-conjunctuur',
                'mantelzorg',
                'maps',
                'markt',
                'markten',
                'meetbout',
                'meetbouten',
                'meldingen',
                'meldpunt',
                'mensen',
                'meta',
                'metadata',
                'meteorologie',
                'meting',
                'metingen',
                'metro',
                'metropoolregio',
                'middelbare',
                'middelbare school',
                'migratieachtergrond',
                'milieu',
                'milieuzone',
                'minima',
                'misdrijven',
                'mobiliteit',
                'moestuin',
                'molen',
                'molens',
                'monitor',
                'monument',
                'monumentaal',
                'monumentcomplex',
                'monumenten',
                'moskee',
                'moskees',
                'moties',
                'motorvoertuigen',
                'musea',
                'museum',
                'muurplanten',
                'muurvlak',
                'muurvlakken',
                'muziek',
                'nationaliteit',
                'nationaliteiten',
                'naturalisatie',
                'natuur',
                'natuurvoedingswinkels',
                'nauwkeurig',
                'nest',
                'nesten',
                'nico',
                'niet-natuurlijk persoon',
                'nieuw',
                'nieuw-west',
                'nieuwbouw',
                'nieuwkomers',
                'noord',
                'nulmeting',
                'nulpunt',
                'nummeraanduiding',
                'nummeraanduidingen',
                'oefentherapeut',
                'oefentherapie',
                'ois',
                'omgeving',
                'omgevingen',
                'omgevingsschade',
                'omgevingsvergunningen',
                'omgevingswet',
                'omgewaaid',
                'omvalling',
                'omzet',
                'ondergrond',
                'onderhoud groenvoorzieningen',
                'onderhoud straten-stoepen',
                'ondernemersvereniging',
                'onderwijs',
                'onderwijsdata',
                'onderwijsniveau',
                'ongelukken',
                'ongevallen',
                'onrechtmatige bewoning',
                'ontmoeting',
                'ontwikkeling',
                'oorspronkelijk bouwjaar',
                'oost',
                'opbrekingen',
                'opbrengsten',
                'open',
                'openbaar',
                'openbaar vervoer',
                'openbare',
                'openbare ruimte',
                'openbare ruimtes',
                'openbareruimte',
                'ophaaldagen grofvuil',
                'ophaaldagen huisvuil',
                'ophalen grofvuil',
                'opheffingen',
                'oplaadpunten',
                'oplaadstations',
                'opladen',
                'opleiding',
                'opleidingsniveau',
                'oppervlakte',
                'oprichtingen',
                'opstal',
                'opvang',
                'opvoeden',
                'opvoedingsondersteuning',
                'ordening',
                'organisaties',
                'orkest',
                'oud',
                'ouderen',
                'ov',
                'overgewicht',
                'overlast',
                'overnachtingen',
                'overzicht',
                'pand',
                'panden',
                'panoramabeeld',
                'panoramabeelden',
                'papier',
                'park',
                'parkeer',
                'parkeerautomaat',
                'parkeerautomaten',
                'parkeerdruk',
                'parkeergarages',
                'parkeergebieden',
                'parkeerkaarten',
                'parkeerplaats',
                'parkeerplaatsen',
                'parkeerplan',
                'parkeerplek',
                'parkeervak',
                'parkeervakken',
                'parkeervergunning',
                'parkeervergunningen',
                'parkeerzones',
                'parkeren',
                'parking',
                'parkingspace',
                'participatie',
                'partnerschappen',
                'partycentra',
                'partylocatie',
                'pc',
                'perceel',
                'perceelgrootte',
                'perceelnummer',
                'percelen',
                'personeel',
                'personeelkosten',
                'personen',
                'persoon',
                'persoonlijke',
                'pipo',
                'plannen',
                'planning',
                'plantsoen',
                'plantsoenen',
                'plastic',
                'plekken',
                'po',
                'podia',
                'politie',
                'politiebureau',
                'politiek',
                'post',
                'postcode',
                'postcode6',
                'postcodes',
                'potentie',
                'praktijk',
                'precies',
                'primair',
                'processie',
                'processierups',
                'producten',
                'prognoses',
                'projecten',
                'projectontwikkelaars',
                'provinciale',
                'provincie',
                'psychiaters',
                'psychiatrie',
                'psychologen',
                'psychotherapeuten',
                'publiekrechtrelijke beperkingen',
                'puntdichtheid',
                'puntenwolk',
                'qwerty',
                'radar',
                'real-time',
                'realisatie',
                'recht',
                'rechten',
                'rechtstoestand',
                'rechtszekerheid',
                'recreatie',
                'rectificatie',
                'reden opvoer',
                'redenopvoer',
                'referendum',
                'referentie',
                'referentiepunt',
                'referentiepunten',
                'regeling',
                'regen',
                'register',
                'registerkinderopvang',
                'registratie meetbouten',
                'reisafstand',
                'reistijd',
                'reistijden',
                'reizen',
                'rekening',
                'religie',
                'remote sensing',
                'restaurant',
                'restaurants',
                'resultaatrekening',
                'resultaten',
                'retributies',
                'ride',
                'rietland',
                'rijden',
                'rijksmonument',
                'rijksmonumenten',
                'rijksmuseum',
                'rollaag',
                'rollagen',
                'routes',
                'ruimte',
                'ruimtelijk',
                'ruimtelijke',
                'ruimtezoekers',
                'rups',
                'ruw',
                'samen',
                'schades',
                'scheidingspercentages',
                'schiphol',
                'scholen',
                'scholier',
                'scholieren',
                'school',
                'schoolgebouwen',
                'schoolverlaters',
                'schoolverzuim',
                'schoolwerktuin',
                'schoolwijzer',
                'schoonhouden',
                'schriftelijke vragen',
                'schuldhulpverlening',
                'secundair',
                'services',
                'shapefile',
                'shoppen',
                'slachtoffer',
                'slachtoffers',
                'snelheid',
                'snelle groeiers',
                'snelweg',
                'snijlijnen',
                'so',
                'sociaal minimum',
                'spanningsindicator',
                'speciaal',
                'speciaal onderwijs',
                'splitsing',
                'splitsingsvergunningen',
                'sport',
                'sportaccommodaties',
                'sportevenement',
                'sportevenementen',
                'sporthal',
                'sporthallen',
                'sportplekken',
                'sportverenigingen',
                'spuiten',
                'staat',
                'stacaravan',
                'stacaravans',
                'stadsarchief',
                'stadsdeel',
                'stadsdeelraad',
                'stadsdelen',
                'stadsgezicht',
                'stadsloods',
                'stadsparken',
                'stadspas',
                'stadsstrand',
                'stallinggedrag',
                'standgegevens',
                'starters',
                'startersvacatures.',
                'startkwalificatie',
                'statistiek',
                'statistieken',
                'status',
                'stedenbouw',
                'stembureau',
                'stembureaus',
                'stemlocaties',
                'stemmen',
                'sterfte',
                'sterren',
                'stoffen',
                'stoplichten',
                'storm',
                'stort',
                'straat',
                'straatnaam',
                'straatnamen',
                'straatnamenregister',
                'straatparkeren',
                'straten',
                'streekproducten',
                'streetview',
                'strooien',
                'strooiroutes',
                'structuur',
                'studenten',
                'studentenhuisvesting',
                'studeren',
                'stukken',
                'subsidie',
                'subsidieregister',
                'subsidies',
                'subsidies.',
                'synagoge',
                'synagoges',
                'talent voor de toekomst',
                'tandarts',
                'tandartspraktijk',
                'tandzorg',
                'tariefgebieden',
                'tarieven',
                'taxi',
                'taxistandplaatsen',
                'technologie',
                'technologievelden',
                'tegels',
                'tempel',
                'tempels',
                'temperatuur',
                'tentoonstellingen',
                'terras',
                'terreinen',
                'terreinmodel',
                'terreinmodellen',
                'tertiar',
                'test',
                'textiel',
                'theater',
                'thuislozen',
                'thuislozenzorg',
                'thuiszorg',
                'tijd',
                'tijdreeks',
                'tiles',
                'toegang',
                'toegankelijkheid',
                'toegevoegde waarde',
                'toerisme',
                'toeristen',
                'toezicht',
                'toneel',
                'topo',
                'topografie',
                'touringcars',
                'trade',
                'tram',
                'transformatie',
                'transparantie',
                'transseksueel',
                'tunnels',
                'tweede',
                'twitter',
                'type woonobject',
                'uitgaan',
                'uitgaanscentrum',
                'uitgave',
                'uitgaven',
                'uitkeringen',
                'uitslagen',
                'uitstroom',
                'unesco',
                'universiteiten',
                'vacatures',
                'vaccinatie',
                'veer',
                'veiligheid',
                'veiligheidsindex',
                'verbeteraspecten buurt',
                'verblijfsobject',
                'verblijfsobjecten',
                'verbruik',
                'verdachten',
                'verdedigingswerk',
                'verdedigingswerken',
                'verdieping toegang',
                'vereniging',
                'vergrijzing.',
                'vergunning',
                'vergunningen',
                'verhuisgeneigdheid',
                'verhuizingen',
                'verhuringen',
                'verhuur',
                'verkeer',
                'verkeersexamen',
                'verkeerslicht',
                'verkeersongevallen',
                'verkeersslachtoffers',
                'verkenningen',
                'verkiezing',
                'verkiezingen',
                'verkiezingsuitslagen',
                'verkochte woningen',
                'verkoopprijs',
                'verkoopprijzen',
                'vermogen',
                'verplaatsingen',
                'verpleeghuizen',
                'verslaafde',
                'verslaafden',
                'verslagen',
                'verslavingszorg',
                'vertragingen',
                'vertrek',
                'vertrektijden',
                'vervoer',
                'verzorgingshuizen',
                'vestiging',
                'vestigingen',
                'vestingen',
                'videoverslagen',
                'vindplaats',
                'vispassage',
                'vloeroppervlakte',
                'voedselwagens',
                'volwasseneneducatie',
                'voorschool',
                'voorstellingen',
                'voortgezet onderwijs',
                'vraag',
                'vrachtverkeer',
                'vrachtwagens',
                'vrije',
                'vrijplaats',
                'vrijwilliger',
                'vruchtgebruik',
                'waardering',
                'wachtlijst',
                'wandkaart',
                'warmte',
                'warmtekoudeopslak',
                'water',
                'waterpassing',
                'waterschap',
                'waterschappen',
                'weer',
                'weg- en waterwerken',
                'wegen',
                'wegenverkeerswet',
                'wegverkeer',
                'wegwerkzaamheden',
                'welstand',
                'welstandsniveau',
                'welstandssysteem',
                'welzijn',
                'werelderfgoed',
                'wereldoorlog',
                'werk',
                'werk in uitvoering',
                'werkenden',
                'werkgelegenheid',
                'werkloosheid',
                'werkloosheidscijfers',
                'werknemers',
                'werkplek',
                'werkplekken',
                'werktijd',
                'werkzaamheden',
                'werkzame',
                'werkzame personen',
                'west',
                'wetenschappelijk onderwijs',
                'wijk',
                'wijkagent',
                'wijkcentrum',
                'wijken',
                'wilde bijen',
                'wildrooster',
                'wind',
                'windenergie',
                'windmolens',
                'windrichting',
                'windvisie',
                'winkelgebied',
                'winkeliers',
                'winkeliersverenigingen',
                'winkels',
                'winkelstraten',
                'winter',
                'wo',
                'wonen',
                'woning',
                'woningbezetting',
                'woningbouw',
                'woningdichtheid',
                'woningen',
                'woningprijs',
                'woningtoewijzigingen',
                'woningvoorraad',
                'woningwaarde',
                'woningzoekenden',
                'woonduur',
                'woonhuis',
                'woonhuizen',
                'woonlasten',
                'woonomgeving',
                'woonplaats',
                'woonplaatsen',
                'wozwaarde',
                'wuygshsgfsj',
                'ww',
                'xyz',
                'zakelijk recht',
                'zakelijke dienstverlening',
                'zakelijke rechten',
                'zakking',
                'zakking cumulatief',
                'zakkingssnelheid',
                'zeehaven',
                'zelfbouw',
                'zelfstandigen',
                'zettingsgedrag',
                'zomer',
                'zomervlucht',
                'zon',
                'zonatlas',
                'zones',
                'zonne-energie',
                'zonnepanelen',
                'zorg',
                'zorgverleners',
                'zuid',
                'zuidoost',
                'zwaluw',
                'zwembad',
                'zwembaden'
              ],
              minLength: 1,
              pattern: '^[^\\n\\r]*?\\S[^\\n\\r]*$',
              type: 'string'
            },
            title: 'Tags',
            type: 'array',
            uniqueItems: true
          },
          'dcat:landingPage': {
            format: 'uri',
            minLength: 1,
            title: 'URL voor meer informatie',
            type: 'string'
          },
          'dcat:theme': {
            default: [],
            items: {
              enum: [
                'theme:none',
                'theme:bestuur-en-organisatie',
                'theme:bevolking',
                'theme:dienstverlening',
                'theme:economie-haven',
                'theme:educatie-jeugd-diversiteit',
                'theme:energie',
                'theme:geografie',
                'theme:milieu-water',
                'theme:openbare-orde-veiligheid',
                'theme:openbare-ruimte-groen',
                'theme:sport-recreatie',
                'theme:stedelijke-ontwikkeling',
                'theme:toerisme-cultuur',
                'theme:verkeer-infrastructuur',
                'theme:verkiezingen',
                'theme:werk-inkomen',
                'theme:wonen-leefomgeving',
                'theme:zorg-welzijn'
              ],
              enumNames: [
                'Overig',
                'Bestuur en organisatie',
                'Bevolking',
                'Dienstverlening',
                'Economie & Haven',
                'Educatie, Jeugd & Diversiteit',
                'Energie',
                'Geografie',
                'Milieu & Water',
                'Openbare orde & veiligheid',
                'Openbare ruimte & groen',
                'Sport & recreatie',
                'Stedelijke ontwikkeling',
                'Toerisme & cultuur',
                'Verkeer & Infrastructuur',
                'Verkiezingen',
                'Werk & Inkomen',
                'Wonen & leefomgeving',
                'Zorg & welzijn'
              ],
              minLength: 1,
              type: 'string'
            },
            title: 'Thema',
            type: 'array',
            uniqueItems: true
          },
          'dct:accrualPeriodicity': {
            default: 'unknown',
            enum: [
              'unknown',
              'realtime',
              'day',
              '2pweek',
              'week',
              '2weeks',
              'month',
              'quarter',
              '2pyear',
              'year',
              '2years',
              '4years',
              '5years',
              '10years',
              'reg',
              'irreg',
              'req',
              'other'
            ],
            enumNames: [
              'onbekend',
              'continu',
              'dagelijks',
              'twee keer per week',
              'wekelijks',
              'tweewekelijks',
              'maandelijks',
              'eens per kwartaal',
              'halfjaarlijks',
              'jaarlijks',
              'tweejaarlijks',
              'vierjaarlijks',
              'vijfjaarlijks',
              'tienjaarlijks',
              'regelmatig',
              'onregelmatig',
              'op afroep',
              'anders'
            ],
            minLength: 1,
            title: 'Wijzigingsfrequentie',
            type: 'string'
          },
          'dct:description': {
            description: 'Geef een samenvatting van de inhoud van de gegevensset, welke gegevens zitten erin en wat is expliciet eruit gelaten',
            minLength: 1,
            title: 'Beschrijving',
            type: 'string'
          },
          'dct:identifier': {
            description: 'Unieke identifier',
            minLength: 1,
            pattern: '^[^\\n\\r]*?\\S[^\\n\\r]*$',
            title: 'UID',
            type: 'string'
          },
          'dct:language': {
            default: 'lang1:nl',
            enum: [
              'lang1:nl',
              'lang1:en'
            ],
            enumNames: [
              'Nederlands',
              'Engels'
            ],
            minLength: 1,
            title: 'Taal',
            type: 'string'
          },
          'dct:publisher': {
            properties: {
              'foaf:homepage': {
                format: 'uri',
                minLength: 1,
                title: 'Website technisch contactpersoon',
                type: 'string'
              },
              'foaf:mbox': {
                format: 'email',
                minLength: 1,
                title: 'E-mail technisch contactpersoon',
                type: 'string'
              },
              'foaf:name': {
                description: 'Geef de naam van de contactpersoon voor technische vragen over de aanlevering. Dit kan dezelfde contactpersoon zijn als voor de inhoudelijke vragen.',
                minLength: 1,
                pattern: '^[^\\n\\r]*?\\S[^\\n\\r]*$',
                title: 'Technisch contactpersoon',
                type: 'string'
              }
            },
            required: [
              'foaf:name'
            ],
            title: '',
            type: 'object',
            'x-order': [
              'foaf:name',
              'foaf:mbox',
              'foaf:homepage'
            ]
          },
          'dct:spatial': {
            description: 'Beschrijving of coördinaten van het gebied dat de gegevensset bestrijkt (boundingbox). Rijksdriehoeksstelsel (pseudo-RD)',
            minLength: 1,
            pattern: '^[^\\n\\r]*?\\S[^\\n\\r]*$',
            title: 'Coördinaten gebiedskader',
            type: 'string'
          },
          'dct:temporal': {
            properties: {
              'time:hasBeginning': {
                description: 'Geef de tijdsperiode aan (begindatum), die de gegevensset beslaat.',
                format: 'date',
                minLength: 1,
                pattern: '^\\d\\d\\d\\d-[01]\\d-[0-3]\\d(?:T[012]\\d:[0-5]\\d:[0-5]\\d(?:\\.\\d+)?)?(?:Z|[01]\\d(?::[0-5]\\d)?)?$',
                title: 'Tijdsperiode van',
                type: 'string'
              },
              'time:hasEnd': {
                description: 'Geef de tijdsperiode aan (einddatum), die de gegevensset beslaat.',
                format: 'date',
                minLength: 1,
                pattern: '^\\d\\d\\d\\d-[01]\\d-[0-3]\\d(?:T[012]\\d:[0-5]\\d:[0-5]\\d(?:\\.\\d+)?)?(?:Z|[01]\\d(?::[0-5]\\d)?)?$',
                title: 'Tijdsperiode tot',
                type: 'string'
              }
            },
            title: '',
            type: 'object',
            'x-order': [
              'time:hasBeginning',
              'time:hasEnd'
            ]
          },
          'dct:title': {
            minLength: 1,
            pattern: '^[^\\n\\r]*?\\S[^\\n\\r]*$',
            title: 'Titel',
            type: 'string'
          },
          'foaf:isPrimaryTopicOf': {
            properties: {
              'dct:issued': {
                default: '2018-07-05',
                description: 'De datum waarop deze beschrijving van de gegevensset beschikbaar is gesteld',
                format: 'date',
                minLength: 1,
                pattern: '^\\d\\d\\d\\d-[01]\\d-[0-3]\\d(?:T[012]\\d:[0-5]\\d:[0-5]\\d(?:\\.\\d+)?)?(?:Z|[01]\\d(?::[0-5]\\d)?)?$',
                title: 'Publicatiedatum',
                type: 'string'
              },
              'dct:modified': {
                default: '2018-07-10',
                description: 'De datum waarop deze beschrijving van de gegevensset voor het laatst is gewijzigd',
                format: 'date',
                minLength: 1,
                pattern: '^\\d\\d\\d\\d-[01]\\d-[0-3]\\d(?:T[012]\\d:[0-5]\\d:[0-5]\\d(?:\\.\\d+)?)?(?:Z|[01]\\d(?::[0-5]\\d)?)?$',
                sysDefined: true,
                title: 'Wijzigingsdatum',
                type: 'string'
              }
            },
            required: [
              'dct:modified'
            ],
            title: '',
            type: 'object',
            'x-order': [
              'dct:issued',
              'dct:modified'
            ]
          },
          'overheid:grondslag': {
            description: 'Geef indien van toepassing aan wat is de oorspronkelijke juridische basis is van de gegevensset.',
            minLength: 1,
            title: 'Juridische grondslag',
            type: 'string'
          },
          'overheidds:doel': {
            description: 'Geef aan met welk doel deze gegevensset is aangelegd. Waarom bestaat deze gegevensset?',
            minLength: 1,
            pattern: '^[^\\n\\r]*?\\S[^\\n\\r]*$',
            title: 'Doel',
            type: 'string'
          }
        },
        required: [
          'dct:title',
          'dct:description',
          'overheidds:doel',
          'foaf:isPrimaryTopicOf',
          'ams:temporalUnit',
          'dct:language',
          'dcat:contactPoint',
          'dct:publisher',
          'dcat:theme',
          'ams:license'
        ],
        type: 'object',
        'x-order': [
          'dct:title',
          'dct:description',
          'dcat:distribution',
          'overheidds:doel',
          'dcat:landingPage',
          'foaf:isPrimaryTopicOf',
          'dct:accrualPeriodicity',
          'dct:temporal',
          'ams:temporalUnit',
          'ams:spatialDescription',
          'dct:spatial',
          'ams:spatialUnit',
          'overheid:grondslag',
          'dct:language',
          'ams:owner',
          'dcat:contactPoint',
          'dct:publisher',
          'dcat:theme',
          'dcat:keyword',
          'ams:license',
          'dct:identifier'
        ]
      },
      'dcat-dataset-list': {
        items: {
          type: 'string'
        },
        type: 'array'
      },
      etag: {
        pattern: '^(?:W/)?\'[^\']+\'$',
        type: 'string'
      }
    },
    securitySchemes: {
      OAuth2: {
        flows: {
          implicit: {
            authorizationUrl: '/oauth2/authorize',
            scopes: {
              'CAT/W': 'Administer the data catalog'
            }
          }
        },
        type: 'oauth2'
      }
    }
  },
  info: {
    title: 'Data catalog',
    version: '1.0.0-alpha'
  },
  openapi: '3.0.0',
  paths: {
    '/datasets': {
      get: {
        description: 'Get a list of all datasets, optionally selected by a free-text query and/or facet filters. This endpoint supports paging using the limit parameter.\nSearch for datasets concerned with jeugdzorg: ``GET /datasets?q=jeugdzorg``\nGet all datasets that have ``jeugdzorg`` as one of its themes:\n``GET /datasets?/properties/dct:theme/items=in=jeugdzorg``\nGet all datasets that have ``jeugdzorg`` or ``ouderenzorg`` as one of their themes:\n``GET /datasets?/properties/dct:theme/items=in=jeugdzorg,ouderenzorg``\nGet all datasets modified in January 2017:\n``GET /datasets?/properties/dct:modified=ge=2017-01-01&/properties/dct:modified=lt=2017-01-31``',
        parameters: [
          {
            description: 'Free-text query',
            in: 'query',
            name: 'q',
            required: false,
            schema: {
              type: 'string'
            }
          },
          {
            description: '**This is a “pseudo-paramemeter”** OpenAPI3 doesn’t allow patterned parameters (yet). Instead, this entry serves as documentation for facet filtering parameters.\nEach facet filter is a ``key=value`` pair in the request query. The *key* consists of a syntactically valid JSON pointer. The *value* starts with one of the following comparators:\n-   ``eq=``: **equals:** True if at least one value matching the JSON\n    pointer is equal to the provided ``value``.\n-   ``in=``: **in:** True if at least one value matching the JSON\n    pointer is equal to at least one of the (comma separated) set of\n    strings in the provided ``value``.\n-   ``ge=``: **greater than or equal to:** True if at least one value\n    matching the JSON pointer is greater than or equal to the provided\n    ``value``.\n-   ``le=``: **less than or equal to:** True if at least one value\n    matching the JSON pointer is less than or equal to the provided\n    ``value``.\n-   ``gt=``: **greater than:** True if at least one value\n    matching the JSON pointer is greater than the provided\n    ``value``.\n-   ``lt=``: **less than:** True if at least one value\n    matching the JSON pointer is less than the provided\n    ``value``.\n\nThis comparator is then followed by a literal, or a comma-separated set of string if the comparator is ``in=``. So example key-value pairs are:\n``/properties/dct:title=in=Hello,world`` The ``dct:title`` property must be either “Hello” or “world”.\n``/properties/dct:title=eq=Hello%20world`` The ``dct:title`` property must be “Hello world”.',
            explode: true,
            in: 'query',
            name: 'any_json_pointer',
            required: false,
            schema: {
              oneOf: [
                {
                  description: 'A string, if the comparator is one of ``=``, ``>``, or ``<``',
                  type: 'string'
                },
                {
                  pattern: '^(/(~0|~1|[^/~<>=])+)+([<>]=|=[=<>~]).+$',
                  type: 'string A set of strings, if the comparator is ``~``'
                }
              ]
            }
          },
          {
            description: 'Amount of results to return',
            in: 'query',
            name: 'limit',
            required: false,
            schema: {
              type: 'integer'
            }
          },
          {
            description: 'Offset in resultset',
            in: 'query',
            name: 'offset',
            required: false,
            schema: {
              type: 'integer'
            }
          }
        ],
        responses: {
          200: {
            content: {
              'application/json': {
                schema: {
                  $ref: '#/components/schemas/dcat-dataset-list'
                }
              }
            },
            description: 'A list of datasets.'
          }
        }
      },
      post: {
        description: 'Upload a new dataset and let the system generate an identifier.',
        requestBody: {
          content: {
            'application/json': {
              schema: {
                $ref: '#/components/schemas/dcat-dataset'
              }
            }
          },
          required: true
        },
        responses: {
          201: {
            description: 'Created.',
            headers: {
              Etag: {
                description: 'Etag of the newly created dataset.',
                schema: {
                  $ref: '#/components/schemas/etag'
                }
              },
              Location: {
                description: 'Location of the newly created dataset.',
                schema: {
                  type: 'string'
                }
              }
            }
          }
        },
        security: [
          {
            OAuth2: [
              'CAT/W'
            ]
          }
        ]
      }
    },
    '/datasets/{id}': {
      delete: {
        description: 'Remove the dataset under the given ID.',
        parameters: [
          {
            in: 'path',
            name: 'id',
            required: true,
            schema: {
              minLength: 1,
              type: 'string'
            }
          },
          {
            description: 'The value *must* be the current `Etag` of the dataset resource, as last seen by the client. This prevents lost updates if multiple clients are concurrently editing the same resource.',
            in: 'header',
            name: 'If-Match',
            required: true,
            schema: {
              $ref: '#/components/schemas/etag'
            }
          }
        ],
        responses: {
          204: {
            description: 'No Content'
          }
        },
        security: [
          {
            OAuth2: [
              'CAT/W'
            ]
          }
        ]
      },
      get: {
        description: 'Get the dataset identified by id.',
        parameters: [
          {
            description: 'This request header can be used to fetch content iff none of the given etags match.',
            in: 'header',
            name: 'If-None-Match',
            required: false,
            schema: {
              type: 'string'
            }
          },
          {
            in: 'path',
            name: 'id',
            required: true,
            schema: {
              minLength: 1,
              type: 'string'
            }
          }
        ],
        responses: {
          200: {
            content: {
              'application/json': {
                schema: {
                  $ref: '#/components/schemas/dcat-dataset'
                }
              }
            },
            description: 'The dataset as a dcat document.',
            headers: {
              Etag: {
                description: 'Etag of the dataset.',
                schema: {
                  $ref: '#/components/schemas/etag'
                }
              }
            }
          },
          304: {
            description: 'Not Modified: The document has an etag that equals one of the given etags in If-None-Match.',
            headers: {
              Etag: {
                description: 'Etag of the dataset.',
                schema: {
                  $ref: '#/components/schemas/etag'
                }
              }
            }
          }
        }
      },
      put: {
        description: 'Upload a dataset under the given ID.',
        parameters: [
          {
            in: 'path',
            name: 'id',
            required: true,
            schema: {
              minLength: 1,
              type: 'string'
            }
          },
          {
            description: 'This request header is required if the client intends to *update* an existing `dataset` resource.  The value *must* be the current `Etag` of the dataset resource, as last seen by the client.  This prevents lost updates if multiple clients are concurrently editing the same resource.',
            in: 'header',
            name: 'If-Match',
            required: false,
            schema: {
              $ref: '#/components/schemas/etag'
            }
          },
          {
            description: 'This request header is required if the client intends to *create* a new `dataset` resource.  This prevents lost updates if multiple clients are concurrently creating the same resource.',
            in: 'header',
            name: 'If-None-Match',
            required: false,
            schema: {
              pattern: '^\\*$',
              type: 'string'
            }
          }
        ],
        requestBody: {
          content: {
            'application/json': {
              schema: {
                $ref: '#/components/schemas/dcat-dataset'
              }
            }
          },
          required: true
        },
        responses: {
          201: {
            description: 'The dataset was succesfully uploaded.',
            headers: {
              Etag: {
                description: 'Etag of the newly created dataset.',
                schema: {
                  $ref: '#/components/schemas/etag'
                }
              },
              Location: {
                description: 'Location of the newly created dataset.',
                schema: {
                  type: 'string'
                }
              }
            }
          },
          204: {
            description: 'The dataset was updated successfully.  The `Etag` response header contains the new Etag.',
            headers: {
              Etag: {
                description: 'New Etag of the updated dataset.',
                schema: {
                  $ref: '#/components/schemas/etag'
                }
              }
            }
          }
        },
        security: [
          {
            OAuth2: [
              'CAT/W'
            ]
          }
        ]
      }
    },
    '/files': {
      post: {
        description: 'Upload a dcat distribution.',
        requestBody: {
          content: {
            'multipart/form-data': {
              schema: {
                properties: {
                  distribution: {
                    format: 'binary',
                    type: 'string'
                  }
                }
              }
            }
          },
          required: true
        },
        responses: {
          201: {
            description: 'Created.',
            headers: {
              Location: {
                description: 'Location of the uploaded distribution.',
                schema: {
                  type: 'string'
                }
              }
            }
          }
        },
        security: [
          {
            OAuth2: [
              'CAT/W'
            ]
          }
        ]
      }
    },
    '/openapi': {
      get: {
        description: 'Get the OpenAPI specification.',
        responses: {
          200: {
            description: 'Success.'
          }
        }
      }
    },
    '/system/health': {
      get: {
        description: 'System health.',
        responses: {
          200: {
            description: 'Plain text description of current system status.'
          }
        }
      }
    }
  },
  servers: [
    {
      url: 'https://acc.api.data.amsterdam.nl/dcatd/'
    }
  ]
};

export default mockApiData;
