import 'angular';
import 'angular-aria';
import 'angular-i18n/nl-nl';
import 'angular-sanitize';
import 'imports-loader?angulartics!angulartics-piwik/src/angulartics-piwik';
import 'leaflet.markercluster';
import 'leaflet-draw';
import 'leaflet-rotatedmarker';
import 'objectFitPolyfill';
