export const REDUCER_KEY = 'cmsData'
export const FETCH_ARTICLES_REQUEST = `${REDUCER_KEY}/FETCH_ARTICLES_REQUEST`
export const FETCH_ARTICLES_SUCCESS = `${REDUCER_KEY}/FETCH_ARTICLES_SUCCESS`
export const FETCH_ARTICLES_FAILURE = `${REDUCER_KEY}/FETCH_ARTICLES_FAILURE`
export const FETCH_PUBLICATIONS_REQUEST = `${REDUCER_KEY}/FETCH_PUBLICATIONS_REQUEST`
export const FETCH_PUBLICATIONS_SUCCESS = `${REDUCER_KEY}/FETCH_PUBLICATIONS_SUCCESS`
export const FETCH_PUBLICATIONS_FAILURE = `${REDUCER_KEY}/FETCH_PUBLICATIONS_FAILURE`

export const fetchArticles = payload => ({
  type: FETCH_ARTICLES_REQUEST,
  payload,
})

export const fetchPublications = payload => ({
  type: FETCH_PUBLICATIONS_REQUEST,
  payload,
})
